gift_card/models.py
from . import db

orderdetails = db.Table('orderdetails', 
db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
db.Column('card_id',db.Integer,db.ForeignKey('card_details.id'),nullable=False),
db.PrimaryKeyConstraint('order_id', 'card_id') ) 


class Card(db.Model):
     __tablename__ = 'card_details'
     id = db.Column(db.Integer, primary_key=True)
     brandname = db.Column(db.String(255), nullable=False)
     title = db.Column(db.String(255), nullable=False)
     offer = db.Column(db.String(500), nullable=False)
     price = db.Column(db.Float, nullable=False)
     image = db.Column(db.String(60), nullable=False)

     def __repr__(self):
          return f"\nID: {self.id}\nTitle: {self.title}\nBrand name: {self.brandname}\nOffer: {self.offer}\nPrice: {self.price}\nImage: {self.image}"


     
class Order(db.Model):
     __tablename__ = 'orders'
     id = db.Column(db.Integer, primary_key=True)
     status = db.Column(db.Boolean, default=False)
     name = db.Column(db.String(64))
     email = db.Column(db.String(128))
     phone = db.Column(db.String(32))
     totalcost = db.Column(db.Float)
     date = db.Column(db.DateTime)
     carddetails = db.relationship("Card", secondary=orderdetails, backref="orders")

     def __repr__(self):
          return f"ID: {self.id}\nStatus: {self.status}\nName: {self.name}\nEmail: {self.email}\nPhone: {self.phone}\nDate: {self.date}\nCard Details: {self.carddetails}\nTotal Cost: ${self.totalcost}"

gift_card/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email

class CheckoutForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    phone = StringField('Phone', validators=[DataRequired()])
    submit = SubmitField('Submit')

gift_card/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
     app = Flask(__name__)
     Bootstrap(app)
     app.debug = True
     
     app.secret_key = 'Giftcard2023secretkey'

     #set the app configuration data 
     app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///card.sqlite'
     
     # initialise db with flask app - necessary because scope of app
     # is only here in create_app, but db is defined globally
     db.init_app(app)
    
     from . import views
     app.register_blueprint(views.main_bp)
     from . import admin
     app.register_blueprint(admin.admin_bp)
     
     @app.errorhandler(404) 
     # Inbuilt function (to Flask) which takes error as parameter
     def not_found(e): 
          return render_template("error.html", error=e)

     # Handles server errors (look-up 'HTTP response status codes')
     @app.errorhandler(500)
     def internal_error(e):
          return render_template("error.html", error=e)
   
     return app
     

gift_card/views.py
from flask import Blueprint, Flask, render_template, url_for, request, session, flash, redirect
from .models import Card, Order
from .forms import CheckoutForm
from datetime import datetime
from . import db

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
     cards = Card.query.all()
     return render_template('index.html' , cards=cards)

@main_bp.route('/search')
def search():
     search = request.args.get('search')
     search = "%{}%".format(search)
     cards= Card.query.filter(Card.offer.like(search) | Card.title.like(search)).all()
     return render_template('index.html', cards=cards)

@main_bp.route('/card/<int:card_id>')
def card(card_id):
     card = Card.query.filter(Card.id == card_id).first()
     return render_template('card.html', card=card)

@main_bp.route('/about')
def about():
     return render_template('about.html')

# Referred to as "Basket" to the user
@main_bp.route('/order', methods=['POST','GET'])
def order():
     card_id = request.values.get('card_id')

     # retrieve order if there is one
     if 'order_id'in session.keys():
          order = Order.query.get(session['order_id'])
          print("yes order exist ")
          # order will be None if order_id stale
     else:
          # there is no order
          order = None

     # create new order if needed
     if order is None:
          order = Order(status = False, name='', email='', phone='', totalcost=0, date=datetime.now())
          try:
               db.session.add(order)
               db.session.commit()
               print(order)
               session['order_id'] = order.id
          except Exception as e:
               print('Oops!! failed at creating a new order, aaya error che bhai')
               order = None

     # calcultate totalprice
     total_price = 0
     if order is not None:
          for card in order.carddetails:
               total_price = total_price + card.price

     # are we adding an item?
     if card_id is not None and order is not None:
          card = Card.query.get(card_id)
          if card not in order.carddetails:
               try:
                    order.carddetails.append(card)
                    db.session.commit()
               except:
                    return 'There was an issue adding the item to your basket'
               return redirect(url_for('main.order'))
          else:
               flash('Item already in basket.')
               return redirect(url_for('main.order'))
     return render_template('order.html', order = order, total_price=total_price)


# Delete specific basket items
@main_bp.route('/deletecard', methods=['POST'])
def deletecard():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        card_to_delete = Card.query.get(id)
        try:
            order.carddetails.remove(card_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting Card from order'
    return redirect(url_for('main.order'))


# Scrap basket
@main_bp.route('/deleteallcard')
def deleteallcard():
    if 'order_id' in session:   
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))



@main_bp.route('/checkout', methods=['POST','GET'])
def checkout():
     form = CheckoutForm() 
     
     if 'order_id' in session:
          order = Order.query.get_or_404(session['order_id'])
          
          if request.method == 'POST':
               order.status = True
               order.name = form.name.data
               order.email = form.email.data
               order.phone = form.phone.data
               totalcost = 0
               for card in order.carddetails:
                    totalcost = totalcost + card.price
               order.totalcost = totalcost
               order.date = datetime.now()
               try:
                    db.session.commit()
                    del session['order_id']
                    flash('Thank you! One of our awesome team members will contact you soon...')
                    return redirect(url_for('main.index'))
               except:
                    return 'There was an issue completing your order'
     return render_template('checkout.html', form=form)

gift_card/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <title>Gifts Kart</title>
</head>
<body>

    <header>
        <h1>Gifts Kart</h1>
        <nav>
            <ul>

                <li><a href="index.html">Home</a></li>
                
            </ul>
        </nav>
    </header>

    <section class="about-us-content">

        <h2>Welcome to Gifts Kart</h2>

        <p>We are committed to providing the best products and services to our customers.</p>

        <p>We offer gift card from various brands. Happy Shopping!</p>

        <h1>For any query email us at support@giftskart.in</h1>

    </section>

    <footer>
        <p>&copy; 2023 Gifts Kart</p>
    </footer>

</body>
</html>

gift_card/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
     <link rel="stylesheet" type="text/css" href="{{url_for('static' ,filename='css/style.css')}}">
     <title>Gifts Card</title>
</head>

<body>
     <nav class="navbar navbar-expand-lg navbar-light " style="background-color: greenyellow;">
          <a class="navbar-brand" href="/">
               <h2>GIFT CARD</h2>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
               aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                         <a class="nav-link text-dark" href="{{url_for('main.about')}}">
                              <h5>About Us</h5>
                         </a>
                    </li>
                    <li>
                         <a class="nav-link text-dark" href="{{url_for('main.order')}}">
                              <h5>Cart</h5>
                         </a>
                    </li>
               </ul>
               <form class="form-inline my-2 my-lg-0" action="{{url_for('main.search')}}">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="search"
                         aria-label="Search">
                    <button class="btn btn-dark my-2 mr-3 my-sm-0" type="submit">Search</button>
               </form>
          </div>
     </nav>


     {% with messages = get_flashed_messages() %}
     {% if messages %}
     <div class="alert alert-primary" role="alert">
          {% for message in messages %}
          {{ message }}
          {% endfor %}
     </div>
     {% endif %}
     {% endwith %}


     {% block head %}

     {% endblock %}




     {% block body %}

     {% endblock body %}

     <footer>
          <p>&copy; 2023 Gifts Card</p>
     </footer>
</body>

</html>

gift_card/templates/card.html
{% extends "base.html" %}

{% block body %}
<!-- card details -->
<div class="container mt-5">
     <div class="row">
          <div class="col-md-6">
               <img src="{{url_for('static', filename='img/'+card.brandname+'.jpg')}}" style="width:500px;" alt="Card" class="product-image">
          </div>
          <div class="col-md-6 product-details">
               <h2>{{card.title}}</h2>
               <p>{{card.offer}}</p>
               <h3>Price: {{card.price}}</h3>
               <form action="{{ url_for('main.order') }}">
                    <input type="hidden" id="card_id" name="card_id" value="{{ card.id }}">
                    <input class="btn btn-outline-dark" style="background-color: greenyellow;" type="submit" value="Add to Basket">
               </form>

               <br><br>
          </div>
     </div>
</div>
{% endblock body %}

gift_card/templates/checkout.html
{% extends "base.html" %}

{% block body %}

<div class="container mt-5 mb-5">
     <h2>Feelup the Details:</h2>
     <br>
     <form action="{{url_for('main.checkout')}}" method="post">
          <div class="form-row ">
               <div class="form-group col-md-6">
                    <label>Name </label>
                    <input type="text" class="form-control" id="name" name placeholder="ex. Mr.Example">
               </div>
          </div>
          <div class="form-row ">
               <div class="form-group col-md-6">
                    <label>Email</label>
                    <input type="email" class="form-control" id="inputEmail" name="email" placeholder="ex. example@gmail.com">
               </div>
          </div>
          <div class="form-row ">
               <div class="form-group col-md-6">
                    <label>Phone</label>
                    <input type="phone" class="form-control" id="phone" name="phone" placeholder="297483131">
               </div>
          </div>
          <button type="submit" class="btn btn-outline-dark"  style="background-color: greenyellow;">Confirm Order</button>
     </form>
</div>

{% endblock body %}

gift_card/templates/error.html
{% extends "base.html" %}
{% block body %}
  <h2>Error..!!</h2>
{% endblock body %}

gift_card/templates/index.html
{% extends "base.html" %}

{% block body %}


<div class="container">
     <h2 class="pb-3">Buy gift card from various brands.</h2>
     <div class="row row-cols-1 row-cols-md-3">
          <!-- show gift card -->
          {% for card in cards %}
          <div class="col mb-4">
               <div class="card">
                    <img src="{{url_for('static', filename='img/'+card.brandname+'.jpg')}}" class="card-img-top"
                         alt="brand image">
                    <div class="card-body">
                         <h4 class="card-title">{{card.title}}</h4>
                         <h6>Price: {{card.price}}</h6>
                    </div>
                    <a href="{{url_for('main.card', card_id=card.id)}}" class="btn btn-outline-dark" style="background-color: greenyellow;">View</a>
               </div>
          </div>
          {% endfor %}
     </div>
</div>

{% endblock body %}

gift_card/templates/order.html
{% extends "base.html" %}

{% block body %}

<section class="h-100" style="background-color: #eee;">
     <div class="container h-100 py-5">
          <div class="row d-flex justify-content-center align-items-center h-100">
               <div class="col-10">

                    <div class="d-flex justify-content-between align-items-center mb-4">
                         <h3 class="fw-normal mb-0 text-black">Shopping Cart</h3>
                    </div>


                    {% for card in order.carddetails %}
                    <div class="card rounded-3 mb-4">
                         <div class="card-body p-4">
                              <div class="row d-flex justify-content-between align-items-center">
                                   <div class="col-md-2 col-lg-2 col-xl-2">
                                        <img src="{{url_for('static', filename='img/'+card.brandname+'.jpg')}}"
                                             class="img-fluid rounded-3" alt="card image">
                                   </div>
                                   <div class="col-md-2 col-lg-3 col-xl-3">
                                        <p class="lead fw-normal mb-2">{{card.title}}</p>
                                   </div>
                                   <div class="col-md-2 col-lg-3 col-xl-2 d-flex">
                                        <input id="form1" min="0" name="quantity" value="1" type="number" class="form-control form-control-sm" />
                                   </div>
                                   <div class="col-md-2 col-lg-2 col-xl-2">
                                        <h5 class="mb-0">${{card.price}}</h5>
                                   </div>
                                   <div class="col-md-2 col-lg-2 col-xl-2">
                                        <form method="POST" action="{{url_for('main.deletecard')}}">
                                             <input type="hidden" id="id" name="id" value="{{card.id}}">
                                             <input type="submit" value="Delete" class="btn btn-danger btn-sm mb-3">
                                        </form>
                                   </div>
                    
                              </div>
                         </div>
                    </div>
                    {% endfor %}

                    <div class="card">
                         <div class="card-body">
                              <a href="{{ url_for('main.deleteallcard') }}" class="btn btn-danger btn-block btn-sm">Empty cart</a>
                              <a href="{{ url_for('main.checkout') }}" class="btn btn-warning btn-block btn-lg">Proceed to Pay
                                   <br>
                                   <span>{{ "$%.2f"|format(total_price) }}</span>
                              </a>
                         </div>
                    </div>

               </div>
          </div>
     </div>
</section>

{% endblock body %}